name: Student Code Test

on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted  # Running on your machine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use System Python (Skip Setup)
        run: python --version  # Check if Python is already installed

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Run Python Tests
        run: python main.py
